# Generated by Django 5.0.1 on 2025-07-22 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'US Dollar'), ('AED', 'UAE Dirham'), ('SDG', 'Sudanese Pound')], max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=16)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('currency_purchase', 'Currency Purchase'), ('partner_deposit', 'Partner Deposit'), ('partner_withdrawal', 'Partner Withdrawal'), ('balance_adjustment', 'Balance Adjustment')], max_length=32)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('sdg_equivalent', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.currency')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='finance.partner')),
            ],
            options={
                'unique_together': {('partner', 'currency')},
            },
        ),
    ]
