# Generated by Django 5.0.1 on 2025-08-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyBalance',
        ),
    ]
