# Generated by Django 5.0.1 on 2025-08-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_delete_companybalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerBalance',
        ),
    ]
