# Generated by Django 5.0.1 on 2025-08-07 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_delete_partnerbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('bought_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=16)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('bought_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_bought', to='finance.currency')),
                ('sold_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_sold', to='finance.currency')),
            ],
        ),
        migrations.DeleteModel(
            name='CurrencyPurchase',
        ),
    ]
