# Generated by Django 6.0.8 on 2026-08-05 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('salesperson', 'Salesperson')], max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('sync_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('stale_write', 'Ignored older change (kept newer data)'), ('oversell', 'Sale exceeded available stock'), ('missing_reference', 'Referenced record not found'), ('error', 'Unexpected error')], max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('incoming', models.JSONField(blank=True, null=True)),
                ('existing', models.JSONField(blank=True, null=True)),
                ('node_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pushed', models.IntegerField(default=0)),
                ('pulled', models.IntegerField(default=0)),
                ('conflicts', models.IntegerField(default=0)),
                ('ok', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('last_pull_cursor', models.DateTimeField(blank=True, null=True)),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('sync_id', models.UUIDField()),
                ('deleted', models.BooleanField(default=False)),
                ('enqueued_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['enqueued_at'],
                'unique_together': {('model_label', 'sync_id')},
            },
        ),
    ]
