# Generated by Django 6.0.8 on 2026-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('sync_id', models.UUIDField()),
                ('sync_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'unique_together': {('model_label', 'sync_id')},
            },
        ),
    ]
