# Generated by Django 6.0.8 on 2026-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_synctombstone'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncstate',
            name='pull_policy',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
