# Generated by Django 5.2.3 on 2025-07-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_commission_paid_commissionpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='paid',
        ),
        migrations.AddField(
            model_name='commission',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
