# Generated by Django 5.0.1 on 2025-08-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='exchange_rate',
            field=models.IntegerField(null=True),
        ),
    ]
