# Generated by Django 5.2.3 on 2025-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_remove_commission_paid_commission_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
