# Generated by Django 5.2.3 on 2025-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_supplier_shipment_supplier_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='free_goods_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
