# Generated by Django 6.0.8 on 2026-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_managercommissionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionpayment',
            name='period_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionpayment',
            name='period_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managercommissionpayment',
            name='period_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managercommissionpayment',
            name='period_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sale_sdg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sale_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
