# Generated by Django 6.0.8 on 2026-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_commissionpayment_period_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='sale_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
